services:
  redis:
    image: "redis:8-alpine"
    container_name: redis
    hostname: '${REDIS_HOST}'
    ports:
      - "${REDIS_PORT}:6379"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - "redis_data:/data"
    env_file:
      - .env

  demo-app:
    ##To build this image:  ./mvnw clean package spring-boot:build-image-no-fork -DskipTests -Dspring-boot.build-image.env.BP_BASE_IMAGE="paketobuildpacks/builder-noble-java-tiny:latest" -Dspring-boot.build-image.env.BP_NATIVE_IMAGE_BUILD_ARGUMENTS="-H:Architecture=linux/amd64"
    image: app/redis-app-sb:v1
    environment:
      REDIS_HOST: '${REDIS_HOST}'
      REDIS_PORT: '${REDIS_PORT}'
      JAVA_TOOL_OPTIONS: '-Xmx300m'
    command: >
      --spring.docker.compose.enabled=false --spring.profiles.active=redis
    ports:
      - "8090:8090"
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env

volumes:
  redis_data:
