## Production profile
spring.docker.compose.enabled=false

## Actuator
management.health.redis.enabled=true

## Spring Redis Configuration (Sentinel)
spring.cache.type=redis
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.sentinel.master=${REDIS_SENTINEL_MASTER:secret}
spring.data.redis.sentinel.nodes=${REDIS_SENTINEL_NODES:redis-sentinel-1:26379,redis-sentinel-2:26379,redis-sentinel-3:26379}

## Redis client behavior for failover-sensitive environments
# This timeout value must be greater that TTL values (default-ttl-value OR correlation-store-ttl-value)
spring.data.redis.timeout=5s
spring.data.redis.connect-timeout=2s
# Add redis connection-factory config for redis-client=lettuce
spring.data.redis.client-type=lettuce
spring.data.redis.lettuce.pool.enabled=true
spring.data.redis.lettuce.pool.max-active=32
spring.data.redis.lettuce.pool.max-idle=16
spring.data.redis.lettuce.pool.min-idle=4
spring.data.redis.lettuce.pool.max-wait=2s

## Keep existing app-level TTL properties (in milliseconds) overridable for prod
app.redis-cache.default-ttl-value=2000
app.redis-cache.correlation-store-ttl-value=3000
